- setup.py
Installing hidapi through pip fails when Cython is not installed
because the import of Cython.Distutils fails.  This patch catches
the exception when importing Cython.Distutils and ignores it.  This
allows setup to complete, even without having Cython already installed.
After the initial installation of hidapi the command build_ext can be
used.
> Fix pip installation error when Cython is missing

- hid.pyx
- setup.py
- detect when exceptions cause the HID device not to be open after call to device.open() (ie. bad serial number)
- check the HID device is actually open before each call that uses self._c_hid
... so we don't have segfaults inside HID library which bring down the entire python world.
I'm obviously smoothing some rough edges that I cut myself on today. No API change just robustness.
> Handle cases where the HID device is closed

- .travis.yml
- README.rst
- setup.py
This option allows to build and install cython-hidapi
with hidraw support only on Linux. Thus libusb dependency
becomes optional.
Because there is no standard support in setuptools for
--with-<feature>/--without-<feature> options during building
we choose the simplest solution suggest at [1].
Also we change the hidraw extension module name from 'hidraw'
to 'hid' in case --without-libusb is specified.
This is required to keep external cython-hidapi API consistent
and not to bother user with backend chosen.
[1] - http://stackoverflow.com/questions/677577/distutils-how-to-pass-a-user-defined-parameter-to-setup-py
fixes #9
> Add --without-libusb option to setup.py

- hid.pyx
Right now, there's no real difference between a failed read and an empty read when polling with "device.read()". 
hidapi already handles this case by returning n of -1 (different from n of 0), but since we populate an array, the array stays empty. And there's no difference for the programmer between an empty read and a failed read. The main use case for this is to tell when the machine has been disconnected.
Unfortunately, this is a breaking change → people working off of the length of the result will get an exception when the response is -1. The other solution I was thinking of was just returning n as a second return value, but that's not backwards compatible either, because then the function would return a tuple.
I tested this on OS X only. I can test on Windows if you'd like, as well.
> Raise IOError on device read() failure

- hid.pyx
Currently, device.open() is an error when the serial_number argument is used.
```python
device.open(0x1941, 0x8021, serial_number=u'0000134865')
device.open(0x1941, 0x8021, serial_number=b'0000134865')
```
[PyUnicode_AsWideChar](https://docs.python.org/3.5/c-api/unicode.html#c.PyUnicode_AsWideChar)
is meant to take a unicode object. When it gets a bytes object, it returns (-1).
This commit changes the type of serial_number to unicode. Now open() works just fine.
Tested on Windows, python 2.7 and python 3.5
> fix serial number type

- MANIFEST.in
- setup.py
Hi,
I just packaged cython-hidapi for Fedora and RHEL7.  As part of my packaging work, I tried to build against the system's hidapi-library, thus I added a switch to setup.py and adjusted the manifest to pick up some useful files into the PyPi-tarball, which need to be included in Fedora's RPM.
> enable build against hidapi installed on system

- setup.py
when hidraw.so is compiled from hid.pyx it has module-init function `inithid` instead if `inithidraw`
> build hidraw.so from hidraw.pyx

- appveyor.yml
This will automatically upload the generated wheels to PyPi whenever a new tag is built 🚀 
To use this you (obviously) have to change the user environment variables.
1. `TWINE_USERNAME` should be a PyPi user with access to the `hidapi` project.
2. `TWINE_PASSWORD` should be the encrypted password for that user. To encrypt it, you can use [this](https://ci.appveyor.com/tools/encrypt) AppVeyor tool.
Secure variables (like `TWINE_PASSWORD`) will not be decrypted for pull requests. 
Related: #44
> Upload to PyPi if a new version is built

- hid.pyx
Addresses [Issue 56](https://github.com/trezor/cython-hidapi/issues/56) - Ensures that errors encountered by the underlying hidapi library on `get_feature_report` are passed up through the cython wrapper.
I verified that the test case where I first observed this throws an error with the change introduced here.
> IOError thrown when get feature report fails

- hid.pyx
All getters above return `-1` if fails according
to HIPAPI lib docs. So `IOError` is raised every
time the getter fails.
Fix #61
> IOError raised when get manufact, sn and product strings fails

- .gitmodules
- README.rst
- setup.py
Per https://github.com/signal11/hidapi/issues/373#issuecomment-498836983, this switches to the `libusb` branch of `hidapi`, as signal11's original branch is no longer maintained.
This pins to the `hidapi-v0.9.0` tag.
> Switch to libusb branch of hidapi

- setup.py
Some *nix operating systems (such as *BSD) store 3rd party libraries along with
their headers in the /usr/local/ prefix instead of /usr/.
> setup.py: Add /usr/local/ prefix to include dirs

- appveyor.yml
(Try to) fix the issues with the AppVeyor builds:
> WIP: Fix build issues on AppVeyor

- chid.pxd
- hid.pyx
* stole the implementation of the "get_feature_report" function and used it to define the "get_input_report" function in the hid.pyx file
* added the "hid_get_input_report" singature in the chid.pxd file
Here's how I tested this:
```python
import hid
d = hid.device()
d.open_path(b'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/Microsoft Pro Intellimouse@14200000/HID KEYBOARD DEVICE@1/AppleUserUSBHostHIDDevice')
d.send_feature_report([0x24,0xB2,0x03,0xFF,0x00,0x00] + [0x00] * 67)
d.send_feature_report([0x24,0xB3] + [0x00] * 71)
d.get_input_report(0x27, 0x29)
```
this should fix #87
> added support for the "get_input_report" function

- chid.pxd
- hid.pyx
At least on linux, while plugging in a faulty hid device, the usb
subsystem tries to enumerate the new device for some time before giving
up. hid_enumerate() will then also block.
this is very unfortunate if a gui thread continuously polls for new
devices. calling hid_enumerate() with the gil released solves this
issue.
Signed-off-by: Martin Gysel <me@bearsh.org>
> call hid_enumerate() without gil

- hid.pyx
> Prevent memory corruption when finalizing HIDAPI

- hid.pyx
Reported-by @bearsh in https://github.com/trezor/cython-hidapi/pull/130#discussion_r741972793.
---
From the documentation:
> It is important to ensure that `func`, `args` and `kwargs` do not own any references to `obj`, either directly or indirectly, since otherwise `obj` will never be garbage collected. In particular, `func` should not be a bound method of `obj`.
The issue wasn't observed during testing, but it may be implementation-defined (as with `__del__`) and depend on specific
combinations of interpreter and Cython versions.
Instead of relying on unspecified behavior, only keep the `hid_device` pointer.  This requires a wrapper because `weakref.finalize()` cannot be passed `cdef` functions or C pointers.
Alternatives were attempted—`__dealloc__`, `weakref.ref(self)`—but they only …
> Remove references to self when creating device finalizers

- hid.pyx
- setup.py
I believe it is good practice to expose the version of python libraries at runtime in the top-level `__version__` attribute.
Depending on how the package was installed, it might be possible to grab the version setup.py used during installation, using importlib, but this is not always the case.
For reference:
```python
>>> import hid
>>> ver1 = hid.__version__
>>>
>>> from importlib.metadata import version
>>> try:
...     ver2 = version("hidapi")
... except ImportError:
...     ver2 = None
...
>>> print(f"{ver1!r}, {ver2!r}")
'0.12.0.post2', '0.12.0.post2'
```
> expose version of bindings as `hid.__version__`

- chid.pxd
- hid.pyx
`hid_version_str` was added to the underlying C library in 0.10.0, in https://github.com/libusb/hidapi/pull/192
Note that the method added here returns the version of the C library,
which is different from the version of cython-hidapi, i.e. the `hid` python package.
It would be good to also make the latter available at runtime (for that, see https://github.com/trezor/cython-hidapi/pull/143 ).
For reference:
```python
>>> import hid
>>> ver1 = hid.version_str()
>>> 
>>> from importlib.metadata import version
>>> try:
...     ver2 = version("hidapi")
... except ImportError:
...     ver2 = None
... 
>>> print(f"{ver1!r}, {ver2!r}")
'0.12.0', '0.12.0.post2'
```
> expose hid_version_str

- .github/workflows/wheels.yml
This should enable the building of wheels for Python 3.11.
Assuming everything goes well here, please upload the Python 3.11 wheels to PyPI when you have some time.
---
In the future, we might want to consider just specifying the major version number, as the cibuildwheel action is probably something we always want to run the latest available (as long as it doesn't do any breaking changes).
> Update cibuildwheel action to 2.11.2

- chid.pxd
- hid.pyx
fixes https://github.com/trezor/cython-hidapi/issues/142
fixes https://github.com/trezor/cython-hidapi/issues/148
note https://github.com/trezor/cython-hidapi/issues/148#issuecomment-1542302679 :
> HIDAPI on macOS has an additional issue regarding thread-safety.
> I did encountered it in my project(s) but didn't have enough time to gather info/find a root cause.
> Looks like on macOS hid_init/hid_exit needs to be called in the same thread,
> which is an additional restriction compared to other platforms.
-----
I have tested on macOS 12.5 (amd64), where using the reproducers in the opening posts of https://github.com/trezor/cython-hidapi/issues/142 and https://github.com/trezor/cython-hidapi/issues/148, I can reproduce a SIGILL (without this patch).
With this patch, there is no SIGILL …
> Call `hid_init()` at import time, to avoid macOS crash

- chid.pxd
- hid.pyx
- To match the original declaration in HIDAPI upstream and avoid compilation errors with newer gcc;
- Include all "system" headers with '<>'; to be explicit that those don't belong to this project/module;
> Fix impropper hid_bus_type declaration

- chid.pxd
- hid.pyx
Added wrapper for `get_report_descriptor` function.
Quite straightforward I think.
Requested by https://github.com/trezor/cython-hidapi/issues/165
> Feature: add get_report_descriptor wrapper

- chid.pxd
- hid.pyx
- use HID_API_MAX_REPORT_DESCRIPTOR_SIZE from hidapi.h
- avoid dynamic memory allocation (use stack variable)
- replace list.append with direct list creation from memory view
> Optimize get_report_descriptor

- setup.py
Hi,
This is Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1083645
or issue #187 here
> avoid generating spurious python3-pkg-resources dependency
